### ISSUE TITLE
Implement authentication for web client

### ISSUE THREAD

**Issue by bryantcj5691** [systemaccounting/mxfactorial#24]
![image](https://cloud.githubusercontent.com/assets/19630795/15988626/c50236ba-3075-11e6-8e72-94905211e40e.png)

to log the user in, web client should call the following endpoint. 
http://apiurl:8080/systemaccounting/users/authenticate (POST)
(username and password should be sent in request body)

upon successful  authentication, endpoint will return the user object an the security token. (see image)

webclient should store this token (in a cookie or browser local storage). Then for each api call, this security token should be appended as the authorization header. 

It is recommended to do this (append token to header) in one place rather than manually adding this to the request for each call. 

![image](https://cloud.githubusercontent.com/assets/19630795/15988654/b134b6a2-3076-11e6-9840-82a22f5e845f.png)

it is also better to log the user out (clear the token from the storage)  (redirect user to login page) whenever some endpoint return unauthorized.

**Comment by frzkhan** [comment]
why not use passportjs for authentication, it generally takes care of all the authentication related stuff

**Comment by mxfactorial** [comment]
@elvongray, please confirm the authentication endpoint added by @bryantcj5691 in https://github.com/systemaccounting/mxfactorial/pull/22 is current with @hotay's changes in https://github.com/systemaccounting/mxfactorial/pull/45 before updating https://github.com/systemaccounting/mxfactorial/pull/27. 

Also, please:
1. edit https://github.com/systemaccounting/mxfactorial/blob/master/account/crud.js#L48 from 'authenticate' to ''/account/auth', and
2. add user-level integration with Firebase services via the "Custom Authentication" documented on https://firebase.google.com/docs/auth/server/ (this project maintains an 'external user system [to] Firebase' because of the dependency transaction data has on account+profile records).

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial/pull/50.
