### ISSUE TITLE
Add /notify service

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#46]
Add a /notify service that manages delivery of multiple notification _types_ through multiple _methods_:

```
{
  "key": "",
  "sender_account": "STRING",
  "receiver_account": "STRING",
  "type": "STRING",
  "method": "STRING",
  "payload": "STRING",
  "sent_time": "DATETIME",
  "received_time": "DATETIME",
}
```

sender & receiver properties record accounts for their values.

Example values for type: 
bid200
ask200
bidReceived200
askReceived200
transact200
accountCreateVerify200
accountCreate200
passwordChangeVerify200
passwordChange200
bidReject200
askReject200

Values for method: 
webclient
email
sms
apns
fcm
api

*Note: [GCM](https://developers.google.com/cloud-messaging/) is replaced by [FCM](https://firebase.google.com/docs/cloud-messaging/); also https://firebase.google.com/support/faq/#messaging-difference

**Comment by mxfactorial** [comment]
@hotay, this task will be completed by @krishnal after @elvongray finishes https://github.com/systemaccounting/mxfactorial/issues/24.

Please comment any relevant Firebase details here to enable the most effective use of its features, and minimize research time of its documentation.

**Comment by hotay** [comment]
{
  "key": "STRING",
  "sender_account": "STRING",
  "receiver_account": "STRING",
  "payload": "STRING/OBJECT",
  "sent_time": "DATETIME",
  "received_time": "DATETIME",
}
- key is the id of an object that has been changed/added/deleted/moved
- payload is the info you want to send to the receiver
- sent_time generate when notification created
- received_time generate when user hit the clearAll button
- the data of object itself must contain sender_account/receiver_account in order to process it

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial/issues/53.
